import { ToolConfig } from "@/types";

export const TOOLS: ToolConfig[] = [
  {
    id: "md-to-pdf",
    name: "MD ⇆ PDF",
    description: "Convert between Markdown and PDF - edit before converting",
    inputLabel: "Markdown",
    outputLabel: "PDF",
    acceptedTypes: ".md,.markdown,.txt",
    maxFiles: 10,
    icon: "FileText",
    category: "convert",
  },
  {
    id: "md-to-docx",
    name: "MD ⇆ DOCX",
    description:
      "Convert between Markdown and Word documents - edit before converting",
    inputLabel: "Markdown",
    outputLabel: "DOCX",
    acceptedTypes: ".md,.markdown,.txt",
    maxFiles: 10,
    icon: "FileText",
    category: "convert",
  },
  {
    id: "md-to-pptx",
    name: "MD → PPTX",
    description: "Convert Markdown to a PowerPoint presentation with an editor",
    inputLabel: "Markdown",
    outputLabel: "PPTX",
    acceptedTypes: ".md,.markdown,.txt",
    maxFiles: 1,
    icon: "Presentation",
    category: "convert",
  },
  {
    id: "pdf-to-md",
    name: "PDF → MD",
    description: "Extract text from PDFs as Markdown with formatting",
    inputLabel: "PDF",
    outputLabel: "Markdown",
    acceptedTypes: ".pdf",
    maxFiles: 10,
    icon: "FileSearch",
    category: "convert",
    hidden: true,
  },
  {
    id: "docx-to-md",
    name: "DOCX → MD",
    description: "Convert Word documents to clean Markdown",
    inputLabel: "DOCX",
    outputLabel: "Markdown",
    acceptedTypes: ".docx",
    maxFiles: 10,
    icon: "FileSearch",
    category: "convert",
    hidden: true,
  },
  {
    id: "image-to-pdf",
    name: "Image ⇆ PDF",
    description:
      "Convert between images and PDF - combine images or extract pages",
    inputLabel: "Images",
    outputLabel: "PDF",
    acceptedTypes: ".png,.jpg,.jpeg,.webp,.gif,.bmp",
    maxFiles: 10,
    icon: "Image",
    category: "convert",
  },
  {
    id: "pdf-to-image",
    name: "PDF → Image",
    description: "Render PDF pages as high-quality images",
    inputLabel: "PDF",
    outputLabel: "Images",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    icon: "Image",
    category: "convert",
    hidden: true,
  },
  {
    id: "pdf-split",
    name: "PDF Split",
    description: "Split a PDF into separate page files",
    inputLabel: "PDF",
    outputLabel: "Split PDFs",
    acceptedTypes: ".pdf",
    maxFiles: 1,
    icon: "Scissors",
    category: "manipulate",
  },
  {
    id: "pdf-merge",
    name: "PDF Merge",
    description: "Combine multiple PDFs into one document",
    inputLabel: "PDFs",
    outputLabel: "Merged PDF",
    acceptedTypes: ".pdf",
    maxFiles: 10,
    icon: "Merge",
    category: "manipulate",
  },
  {
    id: "pptx-builder",
    name: "PPTX Builder",
    description: "Build a PowerPoint presentation with JavaScript",
    inputLabel: "Script",
    outputLabel: "Built PPTX",
    acceptedTypes: ".pptx",
    maxFiles: 10,
    icon: "FileCode",
    href: "/pptx-builder",
    category: "builder",
  },
];

export function getToolConfig(toolId: string): ToolConfig | undefined {
  return TOOLS.find((t) => t.id === toolId);
}
